name: Fitbot AutoBooking

on:
  schedule:
    - cron: '0 13 * * 0,2,4'  # Sunday, Tuesday, Thursday at 9:00 AM Venezuela time (UTC-4)
  workflow_dispatch:  # allows manual run from GitHub UI

jobs:
  run-fitbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run Fitbot
        env:
          AH_USERNAME: ${{ secrets.AH_USERNAME }}
          AH_PASSWORD: ${{ secrets.AH_PASSWORD }}
          AH_BOX_ID: ${{ secrets.AH_BOX_ID }}
          AH_BOX_NAME: ${{ secrets.AH_BOX_NAME }}
          AH_TELEGRAM_BOT_TOKEN: ${{ secrets.AH_TELEGRAM_BOT_TOKEN }}
          AH_CHAT_ID: ${{ secrets.AH_CHAT_ID }}
        run: |
          python src/main.py \
            --booking-goals '{"0": {"time": "0700", "name": "Bee Muscle"}, "2": {"time": "0700", "name": "Bee Muscle"}, "4": {"time": "0700", "name": "Bee Muscle"}}' \
            --days-in-advance 1
